# Generated by Django 2.2.4 on 2019-09-10 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50)),
                ('insurance_number', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=50)),
                ('dob', models.DateTimeField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=50)),
                ('provider_id', models.IntegerField()),
                ('speciality', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.IntegerField()),
                ('claim_date', models.DateTimeField()),
                ('claim_amount', models.IntegerField()),
                ('cust_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c', to='blog.Customers')),
                ('insurance_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d', to='blog.Customers')),
                ('provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to='blog.Providers')),
                ('provider_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a', to='blog.Providers')),
            ],
        ),
    ]
