# Generated by Django 2.2.4 on 2019-09-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claims',
            options={'verbose_name': 'Claim', 'verbose_name_plural': 'Claims'},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='providers',
            options={'verbose_name': 'Provider', 'verbose_name_plural': 'Providers'},
        ),
        migrations.AlterField(
            model_name='customers',
            name='insurance_number',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='providers',
            name='provider_id',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='providers',
            name='speciality',
            field=models.CharField(max_length=100),
        ),
    ]
