# Generated by Django 2.1.7 on 2019-12-09 23:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='claim_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 9, 23, 24, 26, 290740, tzinfo=utc)),
        ),
    ]
