# Generated by Django 2.1.7 on 2019-12-11 02:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191211_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='claim_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 2, 45, 19, 427437, tzinfo=utc)),
        ),
    ]
